### ISSUE TITLE
NoDuplicatedArrayKeyFixer

### ISSUE THREAD

**Issue by realodix** [kubawerlos/php-cs-fixer-custom-fixers#546] opened 2021-06-14 12:45 UTC
```php
$rules = [
  'no_empty_phpdoc' => false,
  'no_empty_phpdoc' => false,
  Fixer\NoDuplicatedArrayKeyFixer::name() => true,
  Fixer\NoDuplicatedArrayKeyFixer::name()     => true,
]
```

Run PHP CS Fixer

```diff
// Actual
 $rules = [
   '@PSR1' => false,
-  '@PSR1' => false,
   Fixer\NoDuplicatedArrayKeyFixer::name() => true,
   Fixer\NoDuplicatedArrayKeyFixer::name() => true,
 ]
```

```diff
// Expected
 $rules = [
   '@PSR1' => false,
-  '@PSR1' => false,
-  Fixer\NoDuplicatedArrayKeyFixer::name() => true,
   Fixer\NoDuplicatedArrayKeyFixer::name() => true,
 ]
```

**Comment by kubawerlos** [comment] 2021-06-16 14:21
The problem is that the function may return different value, like in this case: https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v2.5.0/tests/Fixer/NoDuplicatedArrayKeyFixerTest.php#L86-L88

I think adding an option to to remove expressions will be the best approach: https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/547

**Comment by kubawerlos** [comment] 2021-10-03 11:46
Released in https://github.com/kubawerlos/php-cs-fixer-custom-fixers/releases/tag/v3.0.0

**Closed by kubawerlos** 2021-10-03 11:46 UTC
